# Generated by Django 3.1.6 on 2021-02-13 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('time', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('effectiveness', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('F', 'Failed')], default='P', max_length=1)),
                ('Value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HaBitsApp.habit')),
            ],
        ),
    ]
