# Generated by Django 3.1.6 on 2021-04-26 17:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='NON_VOID_HABIT_TIME_WINDOW',
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(startTime__lt=django.db.models.expressions.F('endTime')), name='habitStartTimeBelowEndTime'),
        ),
    ]
