# Generated by Django 3.1.6 on 2021-02-14 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0002_habit_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='effectiveness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 16, 56, 16, 143014, tzinfo=utc)),
        ),
    ]
