# Generated by Django 3.1.6 on 2021-02-14 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0003_auto_20210214_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
