# Generated by Django 3.1.6 on 2021-02-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0004_auto_20210214_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trace',
            old_name='Value',
            new_name='habit',
        ),
    ]
