# Generated by Django 3.1.6 on 2021-02-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0006_auto_20210219_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name']},
        ),
    ]
