# Generated by Django 3.1.6 on 2021-02-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0007_auto_20210219_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trace',
            options={'ordering': ['date']},
        ),
    ]
