# Generated by Django 3.1.6 on 2021-02-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0008_auto_20210219_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='trace',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
