# Generated by Django 3.1.6 on 2021-02-24 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0009_auto_20210223_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
