# Generated by Django 3.1.6 on 2021-02-24 21:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0010_auto_20210224_2053'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(end_time__gt=django.db.models.expressions.F('start_time')), name='NON_VOID_HABIT_TIME_WINDOW'),
        ),
    ]
