# Generated by Django 3.1.6 on 2021-02-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0011_auto_20210224_2115'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='NON_VOID_HABIT_TIME_WINDOW',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='start_time',
        ),
        migrations.AddField(
            model_name='habit',
            name='end_time_hour',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='end_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_frame',
            field=models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='trace',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trace',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
