# Generated by Django 3.1.6 on 2021-02-25 00:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0012_auto_20210225_0010'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(('end_time_hour__gt', django.db.models.expressions.F('start_time_hour')), ('end_time_hour__lte', 24), ('end_time_minutes__lte', 59), ('start_time_minutes__lte', 59)), name='NON_VOID_HABIT_TIME_WINDOW'),
        ),
    ]
