# Generated by Django 3.1.6 on 2021-02-27 16:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0013_auto_20210225_0011'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='NON_VOID_HABIT_TIME_WINDOW',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='end_time_hour',
            new_name='end_hour',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='end_time_minutes',
            new_name='end_minutes',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='time_frame',
            new_name='range',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='start_time_hour',
            new_name='start_hour',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='start_time_minutes',
            new_name='start_minutes',
        ),
        migrations.AddField(
            model_name='habit',
            name='day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SU', 'Sunday'), ('SA', 'Saturday')], default='', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(('end_hour__gt', django.db.models.expressions.F('start_hour')), ('end_hour__lte', 24), ('end_minutes__lte', 59), ('start_minutes__lte', 59)), name='NON_VOID_HABIT_TIME_WINDOW'),
        ),
    ]
