# Generated by Django 3.1.6 on 2021-03-02 14:31

import HaBitsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0015_auto_20210301_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SU', 'Sunday'), ('SA', 'Saturday')], default=HaBitsApp.models.Habit.today, max_length=2),
        ),
    ]
