# Generated by Django 3.1.6 on 2021-03-02 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0017_auto_20210302_1436'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='NON_VOID_HABIT_TIME_WINDOW',
        ),
        migrations.AlterField(
            model_name='habit',
            name='effectiveness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_hour',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_hour',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(check=models.Q(end_hour__gt=django.db.models.expressions.F('start_hour')), name='NON_VOID_HABIT_TIME_WINDOW'),
        ),
    ]
