# Generated by Django 3.1.6 on 2021-03-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HaBitsApp', '0019_auto_20210302_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='effectiveness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
